name: Release DB Models

on:
  workflow_dispatch:

jobs:
  release:
    name: bump the version and create release notes
    runs-on: ubuntu-latest
    environment: prod

    steps: 
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.8.0 --upgrade
        poetry config virtualenvs.in-project true
        poetry install
    
    - name: bump version
      id: version
      run: |
        echo "tag=v$(poetry version -s)" >> $GITHUB_OUTPUT

    - name: add version tag and push to git
      run: |
        git tag ${{ steps.version.outputs.tag }} && git push --tags
    
    # - name: create release notes
    #   id: release_notes
    #   run: |
    #     echo "release notes" >> $GITHUB_OUTPUT

    
